CREATE TABLE IF NOT EXISTS derechohabientes_padrones_compilado_2025 (
    "acuse_estatal" VARCHAR(30),
    "curp_solicitud" VARCHAR(18),
    "curp_renapo" VARCHAR(18),
    "curp_historica" VARCHAR(18),
    "id_persona" NUMERIC(11),
    "estatus" VARCHAR(29),
    "primer_apellido" VARCHAR(100),
    "segundo_apellido" VARCHAR(100),
    "nombre" VARCHAR(100),
    "nombre_completo" VARCHAR(150),
    "cultivo" VARCHAR(50),
    "clave_estado_predio_inegi" VARCHAR(2),
    "estado_predio_inegi" VARCHAR(50),
    "clave_municipio_predio_inegi" VARCHAR(3),
    "municipio_predio_inegi" VARCHAR(100),
    "clave_localidad_predio" VARCHAR(4),
    "localidad_predio" VARCHAR(150),
    "regimen_hidrico" VARCHAR(3),
    "hect_predio" NUMERIC(10,5),
    "hect_solicita_fert" VARCHAR(25),
    "cuadernillo" VARCHAR(20),
    "nombre_del_ceda" VARCHAR(100),
    "id_ceda_agricultura" VARCHAR(100),
    "superficie" BIGINT,
    "dap_(ton)" NUMERIC(4,3),
    "urea_(ton)" NUMERIC(4,3),
    "fecha_de_publicación" DATE,
    "fecha_de_primer_llamado" DATE,
    "dirección" TEXT,
    "nota_adicional" TEXT
    ,CONSTRAINT pk_derechohabientes_padrones_compilado_2025 PRIMARY KEY ("acuse_estatal")
);